descriptions = [ "Comp", "Precomp",]
default-description = "Comp"
default-padding = "####"
[[comp-templates]]
id = "CompTemplate"
pattern-path = "D:/Freelaance/{project}/{seqencename}/{shotname}/Scripts"
pattern-base = "{seqencename}_{shotname}_{description}_v{version}"
match-end = false
[[comp-templates.outputs]]
id = "Comp"
pattern-path = "D:/Freelaance/{project}/renders/{seqencename}_{shotname}/{shotname}_Comp_v{version}"
pattern-base = "{shotname}_Comp_v{version}"

[[comp-templates.outputs]]
id = "QT"
pattern-path = "D:/Freelaance/{project}/renders/{seqencename}_{shotname}"
pattern-base = "{shotname}_v{version}"

[[comp-templates.outputs]]
id = "Precomp"
pattern-path = "D:/Freelaance/{project}/renders/{seqencename}_{shotname}/{shotname}_Precomp_v{version}"
pattern-base = "{shotname}_Precomp_v{version}"

[[comp-templates.outputs]]
id = "Denoise"
pattern-path = "D:/Freelaance/{project}/renders/{seqencename}_{shotname}/{shotname}_Denoise_v{version}"
pattern-base = "{shotname}_Denoise_v{version}"

[[comp-templates.outputs]]
id = "Matte"
pattern-path = "D:/Freelaance/{project}/renders/{seqencename}_{shotname}/{shotname}_Matte_v{version}"
pattern-base = "{shotname}_Matte_v{version}"

[[comp-templates.outputs]]
id = "Retime"
pattern-path = "D:/Freelaance/{project}/renders/{seqencename}_{shotname}/{shotname}_Retime_v{version}"
pattern-base = "{shotname}_Retime_v{version}"

[[comp-templates.outputs]]
id = "ContactSheet"
pattern-path = "D:/Freelaance/{project}/renders/{seqencename}_{shotname}"
pattern-base = "{shotname}_ContactSheet_v{version}"


[[project-templates]]
id = "Project1"
pattern-path = "D:/Freelaance/{project}/{seqencename}_Scripts"
pattern-base = "{seqencename}{shotname}_v{version}"
match-start = false
match-end = false

